version: '3'

services:
 app:
   ports:
     - "8080:80"
   build: ./docker/app
   container_name: laravel_app
   volumes:
     - ./src:/var/www/html

 minio:
   container_name: minio
   build: ./docker/minio
   command: ['--console-address', ':9001']
   volumes:
     - ./data/minio/data:/export
     - ./data/minio/config:/root/.minio
   ports:
     - 9000:9000
     - 9001:9001
   environment:
     - MINIO_ACCESS_KEY=access
     - MINIO_SECRET_KEY=secretkey

 db:
   image: mysql:5.7
   container_name: laravel_db
   restart: always
   build: ./docker/db
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: laravel_user
     MYSQL_PASSWORD: laravel_pass
     TZ: 'Asia/Tokyo'
   command: --innodb-use-native-aio=0
   volumes:
     - ./docker/db/data:/var/lib/mysql
   ports:
     - 3306:3306
